<?php

namespace Debb\ManagementBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProcessorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProcessorRepository extends EntityRepository
{
}
