<?php

namespace Debb\ConfigBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MainboardRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MainboardRepository extends EntityRepository
{
}
